In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3])
print(arr1)
print(arr1.shape)

[1 2 3]
(3,)


In [4]:
list1 = [1.5, 2.4, 3.7]
print(type(list1))

array1 = np.array(list1)
print(type(array1))

print(array1, array1.dtype)


<class 'list'>
<class 'numpy.ndarray'>
[1.5 2.4 3.7] float64


In [5]:
array_int = np.array([1, 2, 3])
print(array_int, array_int.dtype)

array_float = array_int.astype('float64')
print(array_float, array_float.dtype)


[1 2 3] int32
[1. 2. 3.] float64


In [7]:
sequence_array = np.arange(10)
print(sequence_array)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
zeros1 = np.zeros([3,2])
print(zeros1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
rd = np.random.randn(3,2)
print(rd)

[[ 0.41962982 -1.07373547]
 [ 1.13242697  1.02616057]
 [-0.22771087  1.73845135]]


In [17]:
array1 = np.arange(10)
print("array1:\n", array1)

array2 = array1.reshape(2,5)
print("array2:\n", array2)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
array1 = np.arange(8)

array3d = array1.reshape((2, 2, 2))
print('array3d: \n', array3d)

array2d = array3d.reshape(-1, 1)
print("array2d:\n", array2d)


array3d: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array2d:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [23]:
array1 = np.arange(start=1, stop=10)
array1 = array1.reshape(3,3)

boolean = array1[array1>3]

print('array1 > 3인 불린 인덱싱 결과 값:',  boolean)

print('객체반환: \n', array1>3)

array1 > 3인 불린 인덱싱 결과 값: [4 5 6 7 8 9]
객체반환: 
 [[False False False]
 [ True  True  True]
 [ True  True  True]]


In [24]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('a행렬: \n', a)

b = np.array([[7, 8], [9, 10], [11, 12]])
print('b행렬: \n', b)

print('a와 b의 행렬내적 결과:\n', np.dot(a,b))

a행렬: 
 [[1 2 3]
 [4 5 6]]
b행렬: 
 [[ 7  8]
 [ 9 10]
 [11 12]]
a와 b의 행렬내적 결과:
 [[ 58  64]
 [139 154]]


In [25]:
a = np.array([[1, 2], [3, 4]])
print('a행렬:\n', a)
print('a의 전치행렬:\n', np.transpose(a))


a행렬:
 [[1 2]
 [3 4]]
a의 전치행렬:
 [[1 3]
 [2 4]]


In [26]:
a = np.array([[11, 12, 13], [2, 3, 4]])
print('a행렬:\n', a)
print(a.sum())


a행렬:
 [[11 12 13]
 [ 2  3  4]]
45


In [27]:
print('열 방향 합계: ', a.sum(axis=1))
print('행 방향 합계: ', a.sum(axis=0))


열 방향 합계:  [36  9]
행 방향 합계:  [13 15 17]


In [28]:
print(a.mean())


7.5


In [29]:
print(a.prod())


41184


In [34]:
print(a.max())
print(a.min())
print(a)

13
2
[[11 12 13]
 [ 2  3  4]]


In [33]:
print(a.argmax())
print(a.argmin())
# .argmax()와 .argmin()을 이용하여 배열에서 최댓값인 원소의 인덱스 번호와 최솟값인 원소의 인덱스 번호를 구할 수 있습니다.


2
3
